### PR TITLE
Favourite products tab

### PR DESCRIPTION
**Pull request by Jorrre**
This adds a favourite products tab for users with previous purchases. If a user has purchased more than five different products, the favourite products tab will be set automatically on login.

The favourite products are stored as a part of the User type.

This PR has to wait until OW4 adds functionallity for fetching a users purchase history (https://github.com/dotkom/onlineweb4/pull/2617)

Refs: #44

### CODE REVIEW

**Comment by Jorrre** [comment]
So the required endpoint is up, but it is pretty slow. Should we still go ahead with this?

**Comment by MartinSkatvedt** [comment]
Tried it out but did not find it slow. However the category button looks wierd (the text is on two lines), perhaps change it to only "favourites". Also could it be an idea to have it as the first page?

**Review by MartinSkatvedt — APPROVED** [review]
LGMT! Changed the name from "dine favoritter" to "mest kjøpt" as the text wrapped. 

Good job!

**Comment by Jorrre** [comment]
@Chaaarles should probably try it out first, as a stress test for the endpoint ;)

**Comment by Jorrre** [comment]
> LGMT! Changed the name from "dine favoritter" to "mest kjøpt" as the text wrapped.
> 
> Good job!

Might be ambigous as this can both mean "Produkter som *du* har kjøpt ofte" and "Produkter som generelt blir kjøpt ofte av nibble-brukere". What about decreasing font size or increasing box size

**Comment by MartinSkatvedt** [comment]
> > LGMT! Changed the name from "dine favoritter" to "mest kjøpt" as the text wrapped.
> > Good job!
> 
> Might be ambigous as this can both mean "Produkter som _du_ har kjøpt ofte" and "Produkter som generelt blir kjøpt ofte av nibble-brukere". What about decreasing font size or increasing box size?

I see, the text should propably be "dine favoritter" then. Then we have some solutions:
1. Make all category sizes dynamic
2. Smaller font size
3. Only make the "dine favoritter" category box bigger

**Comment by Jorrre** [comment]
Good idea, I think I like alternative 1 best. Another soloution would be to increase the sizes of all the boxes, but I dont know if that's gonna look weird on the boxes with less text. 

Also, my browser scales things differently than the kiosk PC so someone else has to try out the changes. 

Side note: the kiosk PC has the browser zoom set to 80%, keep that in mind

**Comment by MartinSkatvedt** [comment]
I just made every category 10%, this makes the whole category bar fill the top of the shop. This looks like the best option.

image

**Pull request merged**
