### PR TITLE
reduce size of nav bar and space out elements

### PR DESCRIPTION
**Pull request by Paalar**

### CODE REVIEW

**Review by MartinSkatvedt — COMMENTED** [review]
Check out #16 
This solves the user in navbar, in additon to other things. In my opinion we should merge #16 and  fix the styling after.

**Comment by Paalar** [comment]
I have now merged #16 into this branch.

**Review by MartinSkatvedt — APPROVED** [review]
Logout icon should be moved more right, but this can be fixed when we implement user logout!

**Comment by Paalar** [comment]
> Logout icon should be moved more right, but this can be fixed when we implement user logout!

It was just a problem when removing the wrapping div! Fixed it now.

**Pull request merged**
