### PR TITLE
Add sound effect on purchase #49

### PR DESCRIPTION
**Pull request by Chaaarles**
Adds funny epic sound effects on purchase
Maybe even get named king of the castle you big spendor you !

### CODE REVIEW

**Comment by Jorrre** [comment]
Wow, looks super epic👌🤌

**Comment by Chaaarles** [comment]
Adresses issue #49

**Comment by MartinSkatvedt** [comment]
NGL, sounds kinda epic. But should implement #48 first.

**Comment by MartinSkatvedt** [comment]
LGTM

**Pull request merged**
